spring.application.name=labjc-web


spring.datasource.url=jdbc:mariadb://localhost:3306/labjc_db


spring.datasource.username=${LABJC_DB_USER}
spring.datasource.password=${LABJC_DB_PASSWORD}
labjc.downloads.path=${LABJC_DOWNLOADS_PATH:/opt/labjc-web/downloads}


spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


spring.jpa.hibernate.ddl-auto=update