-- Tabla de posts (blog) - compatible H2
CREATE TABLE posts (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug             VARCHAR(160) UNIQUE NOT NULL,
  titulo           VARCHAR(200) NOT NULL,
  resumen          CLOB,
  contenido_md     CLOB NOT NULL,
  etiquetas        VARCHAR(255),
  publicado        BOOLEAN NOT NULL DEFAULT FALSE,
  creado           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado      TIMESTAMP NULL
);

-- Tabla de proyectos
CREATE TABLE proyectos (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo           VARCHAR(200) NOT NULL,
  descripcion_md   CLOB NOT NULL,
  stack            VARCHAR(255),
  enlace           VARCHAR(255),
  destacado        BOOLEAN NOT NULL DEFAULT FALSE,
  creado           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de descargas (con contador privado)
CREATE TABLE descargas (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre            VARCHAR(200) NOT NULL,
  ruta_archivo      VARCHAR(255) NOT NULL,
  checksum_sha256   VARCHAR(64),
  habilitado        BOOLEAN NOT NULL DEFAULT TRUE,
  total_descargas   BIGINT NOT NULL DEFAULT 0
);

-- Tabla de visitas (para estadísticas internas)
CREATE TABLE visitas (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ruta    VARCHAR(255) NOT NULL,
  fecha   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Índices
CREATE INDEX idx_posts_publicado_creado     ON posts(publicado, creado);
CREATE INDEX idx_proyectos_destacado_creado ON proyectos(destacado, creado);
CREATE INDEX idx_visitas_ruta_fecha         ON visitas(ruta, fecha);
